###### Config

baseurl = "https://getsol.us/"
title = "Solus"

###### Modules


###### Content
buildDrafts = false
buildFuture = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
googleanalytics = "UA-Not-Yet"
metaDataFormat = "toml"
pagination.pagerSize = 5
summaryLength = 25
theme = ["blog", "solus"]
enableInlineShortcodes = true

###### Special Params

[params]
	domain = "getsol.us"
	category = ["budgie", "infrastructure", "news", "packages", "partners", "plans", "releases", "security", "roundup", "twis"]
	copyright = "2024"

[params.menus]
	main = [ "home", "about", "blog", "download", "dev_tracker", "forums", "funding", "help", "matrix"]
	footer = [ "solus", "social", "support", "press"]
	solus = [ "about", "download", "experiences",  "technologies" ]
	social = [ "facebook", "mastodon", "reddit", "twitch"]
	support = ["dev_tracker", "forums", "funding", "help", "matrix"]
	press = ["branding", "press"]

[params.menuurls]
	about = "/solus/about"
	home = ""
	blog = "blog"
	branding = "branding"
	budgie = "budgie"
	dev_tracker = "https://dev.getsol.us"
	download = "download"
	experiences = "/solus/experiences"
	facebook = "https://facebook.com/get.solus"
	forums = "https://discuss.getsol.us"
	funding = "https://opencollective.com/getsolus"
	get_involved = "/help/contributing/getting-involved/"
	help = "https://help.getsol.us/"
	mastodon = "https://fosstodon.org/@Solus"
	matrix = "https://matrix.to/#/#solus:matrix.org"
	press = "press"
	reddit = "https://www.reddit.com/r/SolusProject"
	support_us = "/help/contributing/getting-involved/"
	team = "/solus/team"
	technologies = "/solus/technologies"
	twitter = ""
	twitch = "https://twitch.tv/getsolus"

[params.teams]
	list = ["beatrice", "friedrich", "joe", "pierre"]

# Rendering

[markup.goldmark.renderer]
    unsafe = true

[minify]
    minifyOutput = true

[minify.tdewolff.html]
    keepWhitespace = true
